# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Restore dependencies
      run: dotnet restore LemmyNanny/LemmyNanny.csproj
    - name: Build
      run: dotnet build --no-restore LemmyNanny/LemmyNanny.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal LemmyNanny/LemmyNanny.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/LemmyNanny/LemmyNanny/dotNETLemmy/dotNETLemmy.API/bin/Debug/net8.0/
          
